export const baseUrl = "http://localhost:1220"
export const emergenciesUrl = baseUrl + "/emergencies"
export const subscribeUrl = baseUrl + "/subscribe"
export const w3css = "https://www.w3schools.com/w3css/4/w3.css"
export const publicServerKey = "BAxxCtddG2073Gixr4PQdzukDGWT0he3q7PNiSESchoyfCEqfTlq9W-XSymOinYJTe04r4SI0fuQlTJu1Z67LKw"
